"""add paper_supervisors table

Revision ID: 725ab16bfad1
Revises: 170ae67b2b24
Create Date: 2026-07-22 05:02:45.544109
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '725ab16bfad1'
down_revision = '170ae67b2b24'
branch_labels = None
depends_on = None

from sqlalchemy.dialects import postgresql


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper_annotations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_annotations_author_id'), 'paper_annotations', ['author_id'], unique=False)
    op.create_index(op.f('ix_paper_annotations_id'), 'paper_annotations', ['id'], unique=False)
    op.create_index(op.f('ix_paper_annotations_paper_id'), 'paper_annotations', ['paper_id'], unique=False)
    op.create_table('paper_supervisors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_supervisors_id'), 'paper_supervisors', ['id'], unique=False)
    op.create_index(op.f('ix_paper_supervisors_paper_id'), 'paper_supervisors', ['paper_id'], unique=False)
    op.create_index(op.f('ix_paper_supervisors_user_id'), 'paper_supervisors', ['user_id'], unique=False)
    op.alter_column('department_supervisors', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_department_supervisors_id'), 'department_supervisors', ['id'], unique=False)
    op.drop_index('ix_paper_versions_paper_version_no', table_name='paper_versions')
    op.create_foreign_key(None, 'papers', 'users', ['external_examiner_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'papers', 'users', ['lecturer_approved_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'papers', 'users', ['project_coordinator_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'papers', 'users', ['hod_approved_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'papers', 'users', ['internal_examiner_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'papers', 'users', ['project_coordinator_approved_by_id'], ['id'], ondelete='SET NULL')
    op.drop_column('papers', 'lecturer_overdue_alert_sent_at')
    op.create_index(op.f('ix_students_department'), 'students', ['department'], unique=False)
    op.create_index(op.f('ix_students_school'), 'students', ['school'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_students_school'), table_name='students')
    op.drop_index(op.f('ix_students_department'), table_name='students')
    op.add_column('papers', sa.Column('lecturer_overdue_alert_sent_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'papers', type_='foreignkey')
    op.drop_constraint(None, 'papers', type_='foreignkey')
    op.drop_constraint(None, 'papers', type_='foreignkey')
    op.drop_constraint(None, 'papers', type_='foreignkey')
    op.drop_constraint(None, 'papers', type_='foreignkey')
    op.drop_constraint(None, 'papers', type_='foreignkey')
    op.create_index('ix_paper_versions_paper_version_no', 'paper_versions', ['paper_id', 'version_no'], unique=True)
    op.drop_index(op.f('ix_department_supervisors_id'), table_name='department_supervisors')
    op.alter_column('department_supervisors', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_paper_supervisors_user_id'), table_name='paper_supervisors')
    op.drop_index(op.f('ix_paper_supervisors_paper_id'), table_name='paper_supervisors')
    op.drop_index(op.f('ix_paper_supervisors_id'), table_name='paper_supervisors')
    op.drop_table('paper_supervisors')
    op.drop_index(op.f('ix_paper_annotations_paper_id'), table_name='paper_annotations')
    op.drop_index(op.f('ix_paper_annotations_id'), table_name='paper_annotations')
    op.drop_index(op.f('ix_paper_annotations_author_id'), table_name='paper_annotations')
    op.drop_table('paper_annotations')
    # ### end Alembic commands ###
